### ISSUE TITLE
Enable more React rules

### ISSUE THREAD

**Issue by fregante** [pixiebrix/eslint-config-pixiebrix#194]
Once all of the rules mentioned on this issue are merged or closed, let's use this issue to migrate those rules from the Extension's `eslintrc.js` to eslint-config-pixiebrix.

Notes
---

The config only uses the recommended list, but apparently there are lot more rules:

https://github.com/jsx-eslint/eslint-plugin-react/tree/master#list-of-supported-rules

A very useful one is `react/jsx-no-useless-fragment`, which I'll enable soon in a PR.

**Q: Do you see any other rules that might be useful in that list?**

Note: A lot of them are formatting related and that's already taken care by Prettier.

**Comment by grahamlangford** [comment]
* https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md -- using the index key is useless since that's the default behavior
  * https://github.com/pixiebrix/pixiebrix-extension/pull/7567
* https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-object-type-as-default-prop.md
    * https://github.com/pixiebrix/pixiebrix-extension/pull/7704
* https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unstable-nested-components.md
  * https://github.com/pixiebrix/pixiebrix-extension/pull/7817


Low Priority
---
* https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/forbid-elements.md -- prefer `<strong>` to `<b>` and `<em>` to `<i>`
  * https://github.com/pixiebrix/pixiebrix-extension/pull/7817
* https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-max-depth.md
  * https://github.com/pixiebrix/pixiebrix-extension/pull/7819

**Comment by grahamlangford** [comment]
Not a react rule, but another good one that I want to keep track of: https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/prefer-expect-resolves.md

* Implemented here: https://github.com/pixiebrix/pixiebrix-extension/pull/7816

**Comment by fregante** [comment]
Changing the intent/title of issues makes it confusing for the links that already point to it. I'll open a new issue to track the migration since this one is completed:


- https://github.com/pixiebrix/eslint-config-pixiebrix/issues/237
